project:
  type: website
  pre-render: bash sync-docs.sh
  # resources:
  #   - styles.css

website:
  title: "PRISM" 
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: guide/developer.qmd
        text: Admin Guide
      - href: guide/user.qmd
        text: User Guide
      - href: guide/background.qmd
        text: Background
  google-analytics:
    tracking-id: "G-XXXXXXXX"
    storage: cookies
    anonymize-ip: true
  repo-url: https://github.com/Australian-Future-Hearing-Initiative/prism-docs
  repo-actions: [edit]

format:
  html:
    # css: styles.css
    toc: true
    toc-depth: 2
    code-overflow: wrap
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly