### 1. Prerequisites
Ensure the following are installed and running:
- [**Docker Desktop**](https://desktop.docker.com/) 
- [**Git** for Windows](https://git-scm.com/download/win), or for Mac and Linux git is pre-installed.
- [A **Firebase** project](https://console.firebase.google.com/) with paid usage enabled.
- [A **Mailgun** account](https://www.mailgun.com/) for sending emails.

### 2. First-time Setup

#### 1. **Clone the repository**:

Clone this repository and move into it.

```bash
git clone https://github.com/Australian-Future-Hearing-Initiative/prism-setup.git
cd prism-setup
```

#### 2. Configure your keys and secrets:

Create a `.env` file in the `prism-setup` directory with the following keys.

##### 1. **JWT Secret**

Generate a unique secret for your session tokens using
`openssl rand -hex 32` or from https://jwtsecretkeygenerator.com/ the set the value:

```dotenv
JWT_SECRET=xxxx
```

##### 2. **Email Settings**

**Option A: Mailgun**

1. Sign up for a free account at https://www.mailgun.com/
2. Follow the instructions to add a domain and verify your email address.
3. Copy the API key and domain name into your `.env` file.

```dotenv
MAILGUN_API_KEY=xxxx
MAILGUN_AUTHORIZED_DOMAIN=xxxx.mailgun.org
```

**Option 2. Via Gmail's SMTP server**

To allow PRISM to send emails via Gmail, you need to enable 2-Step Verification and generate an App Password.
* **Gmail App Password (MAIL_PASSWORD)**: [Google Account](https://myaccount.google.com/security) → Security & Sign-in → turn 2‑Step Verification ON
* Then navigate to your [App passwords](https://myaccount.google.com/apppasswords) → create a new app password, give it a name (`PRISM`) copy the 16‑char code (no spaces) into MAIL_PASSWORD.

Add the following to your `.env` file:

```dotenv
MAIL_USERNAME=xxxxx@gmail.com
MAIL_FROM=xxxxxx@gmail.com            # must match or be a verified alias
MAIL_PASSWORD=xxxxxxxxxxxxxxxx      # 16‑char Google App Password, NOT EMAIL PASSWORD, see below
MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_STARTTLS=True                  # or: MAIL_PORT=465 + MAIL_SSL_TLS=True
MAIL_SSL_TLS=False
MAIL_FROM_NAME=PRISM
USE_CREDENTIALS=True
VALIDATE_CERTS=True
```

##### 3. **Firebase Web API Key**

> You must have access to a paid Firebase project with an "Editor" or "Owner" role to be able to get a private key.

From the Firebase Console, find it in 
**PrismData → Project settings → General** 

Scroll down to **Your apps → Web apps → prism (web) → Config (radio button) > apiKey**, then add:

```dotenv
FIREBASE_API_KEY=xxxxx
```

Replace *PrismData* and *prism (web)* with the corresponding names of your Firebase project and web app.

##### 4. **Firebase Service Account Key file**

From the Firebase Console: 
**PrismData → Project settings → Service accounts → Firebase Admin SDK → Generate new private key**.

Rename the file to `serviceAccountKey.json` and place it in the `prism-setup` directory, then add:
```dotenv
FIREBASE_KEY_PATH=./serviceAccountKey.json
```


### 3. Run the installer script:
```bash
bash install.sh
```  
This will create the Dockerfiles for the backend and frontend, clone the repos and check for the presence of your keys. If it fails, simply fix the errors as suggested and run the script again.


### 4. Launch PRISM
Now to launch the frontend and backend services on your local machine run:

```Bash
docker compose up --build
```
Wait until setup completes then interact with the app via:  

* **Frontend Dashboard**: http://localhost:3000
* **Backend API**: http://localhost:8000

To stop the frontend and backend services run:

```Bash
docker compose down
```


### 5. Deploy to production
TODO